[package]
name = "gbar"
version = "0.1.0"
authors = ["chibinz <chibinzhang@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
console = { path = "../console" }
minifb = "0.15"
env_logger = "0.8"
