[package]
name = "gbar"
version = "0.1.0"
authors = ["chibinz <chibinzhang@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
gba = { path = "../gba" }
minifb = "0.20"
env_logger = "0.8"
backtrace = "0.3"
