[package]
name = "cpu"
version = "0.1.0"
authors = ["Chibin Zhang <chibinzhang@hotmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util" }
